import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const source=path.resolve('build/web'),target=path.resolve('docs/app');
if(!fs.existsSync(path.join(source,'main.dart.js'))) throw new Error('Run flutter build web first');
fs.mkdirSync(path.join(source,'licenses'),{recursive:true});
for(const font of ['Lora','Manrope','Roboto']) fs.copyFileSync(`assets/fonts/${font}-OFL.txt`,path.join(source,'licenses',`${font}-OFL.txt`));
fs.mkdirSync(target,{recursive:true});
function list(dir,prefix='') {return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?list(path.join(dir,e.name),prefix+e.name+'/'):[prefix+e.name]);}
// The loader explicitly uses the full CanvasKit renderer. Omit unused variants.
const files=list(source).filter(f=>!f.endsWith('.map')&&!f.endsWith('.symbols')&&(!f.startsWith('canvaskit/')||['canvaskit/canvaskit.js','canvaskit/canvaskit.wasm'].includes(f))&&!f.includes('skwasm')&&!f.startsWith('canvaskit/chromium/')&&!['.last_build_id','flutter_service_worker.js','sw.js'].includes(f));
for(const file of files){fs.mkdirSync(path.dirname(path.join(target,file)),{recursive:true});fs.copyFileSync(path.join(source,file),path.join(target,file));}
for(const stale of list(target).filter(f=>!files.includes(f)&&f!=='sw.js')) {
 const resolved=path.resolve(target,stale);
 if(!resolved.startsWith(target+path.sep)) throw new Error('Invalid generated file path');
 fs.unlinkSync(resolved);
}
const hash=crypto.createHash('sha256');
for(const file of files.sort()){hash.update(file);hash.update(fs.readFileSync(path.join(target,file)));}
const version=hash.digest('hex').slice(0,12);
const cacheName='stillword-app-'+version;
const worker=`// Generated by tool/package-web.mjs. Caches only the iPhone app, never the APK or landing page.
const CACHE=${JSON.stringify(cacheName)};
const FILES=${JSON.stringify(files)};
self.addEventListener('install',event=>event.waitUntil((async()=>{
 const cache=await caches.open(CACHE);
 try { await cache.addAll(FILES.map(file=>new Request(new URL(file,self.registration.scope),{cache:'reload'}))); }
 catch(error) { await caches.delete(CACHE); throw error; }
 await self.skipWaiting();
})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{
 for(const key of await caches.keys()){if(key.startsWith('stillword-app-')&&key!==CACHE)await caches.delete(key);}
 await self.clients.claim();
})()));
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);
 if(event.request.method!=='GET'||!url.href.startsWith(self.registration.scope))return;
 event.respondWith((async()=>{
   const cache=await caches.open(CACHE);
   if(event.request.mode==='navigate')return await cache.match(new URL('index.html',self.registration.scope).href)||fetch(event.request);
   return await cache.match(event.request,{ignoreSearch:true})||fetch(event.request);
 })());
});
`;
fs.writeFileSync(path.join(target,'sw.js'),worker);
console.log(`Packaged ${files.length} files; offline cache ${cacheName}; ${(files.reduce((n,f)=>n+fs.statSync(path.join(target,f)).size,0)/1048576).toFixed(1)} MiB`);
